# Generated by Django 3.2.6 on 2021-09-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/profiles/default_profile.jpg', null=True, upload_to='profiles/'),
        ),
    ]
