# Generated by Django 3.2.6 on 2021-09-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/profiles/default/default_profile.jpg', null=True, upload_to='images/profiles/'),
        ),
    ]
