# Generated by Django 3.2.7 on 2021-09-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_review_body'),
        ('users', '0006_auto_20210909_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='trade',
            field=models.ManyToManyField(to='dashboard.TradePosition'),
        ),
    ]
