# Generated by Django 3.2.7 on 2021-09-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_review_body'),
        ('users', '0007_messages_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='trade',
            field=models.ManyToManyField(related_name='trade', to='dashboard.TradePosition'),
        ),
    ]
