# Generated by Django 3.2.7 on 2021-09-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeposition',
            name='side',
            field=models.CharField(choices=[('Long', 'Long'), ('Short', 'Short')], max_length=200),
        ),
    ]
