# Generated by Django 3.2.7 on 2021-09-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_tradeposition_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeposition',
            name='side',
            field=models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], max_length=5),
        ),
    ]
