# Generated by Django 3.2.7 on 2021-10-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_tradeposition_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='emotion',
            field=models.CharField(choices=[('fear', 'Fear'), ('hope', 'Hope'), ('stress', 'Stress'), ('calm', 'Calm'), ('happy', 'Happy'), ('sad', 'Sad')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tradeposition',
            name='side',
            field=models.CharField(choices=[('Long', 'Long'), ('Short', 'Short')], max_length=6),
        ),
    ]
