# Generated by Django 3.2.6 on 2021-08-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_analysis_chartpatterns_harmonicpatterns_technicalindicators_tradeposition_trendanalysis_waveanalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeposition',
            name='side',
            field=models.CharField(max_length=200),
        ),
    ]
