# Generated by Django 3.2.7 on 2021-10-01 18:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_tradeposition_strategyalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='remainRisk',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
