# Generated by Django 3.2.7 on 2021-09-05 13:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210905_1305'),
        ('dashboard', '0010_alter_tradeposition_side'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradeposition',
            name='leverage',
        ),
        migrations.AddField(
            model_name='tradeposition',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
        migrations.AlterField(
            model_name='tradeposition',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tradeposition',
            name='size',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
