# Generated by Django 3.2.7 on 2021-09-08 08:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210905_1305'),
        ('dashboard', '0011_auto_20210905_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('emotion', models.CharField(choices=[('fear', 'Fear'), ('hope', 'Hope'), ('stress', 'Stress'), ('calm', 'Calm'), ('happy', 'Happy'), ('sad', 'Sad')], max_length=200)),
                ('body', models.TextField(blank=True, max_length=2000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.tradeposition')),
            ],
        ),
    ]
