# Generated by Django 3.2.7 on 2021-10-01 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20211001_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remainrisk',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remainrisk', to='dashboard.strategy'),
        ),
    ]
