# Generated by Django 3.2.7 on 2021-09-08 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='trade',
        ),
        migrations.AddField(
            model_name='tradeposition',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.review'),
        ),
    ]
