# Generated by Django 3.2.7 on 2021-09-09 19:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_delete_messages'),
        ('dashboard', '0015_alter_review_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messeges', to='users.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg', to='dashboard.tradeposition')),
            ],
            options={
                'ordering': ['is_read', '-created'],
            },
        ),
    ]
