# Generated by Django 3.2.7 on 2021-10-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_delete_remainrisk'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='remain_risk',
            field=models.FloatField(null=True),
        ),
    ]
