# Generated by Django 3.2.7 on 2021-10-02 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_strategy_remain_risk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategy',
            old_name='remain_risk',
            new_name='new_position_size',
        ),
    ]
