# Generated by Django 3.2.7 on 2021-09-24 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_delete_messages'),
        ('dashboard', '0018_auto_20210910_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='Chart_Patterns',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='Technical_Indicators',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='WaveAnalysis',
        ),
        migrations.AddField(
            model_name='analysis',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='trade',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='dashboard.tradeposition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='harmonicpatterns',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
        migrations.AddField(
            model_name='trendanalysis',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='Harmonic_Patterns',
        ),
        migrations.AddField(
            model_name='analysis',
            name='Harmonic_Patterns',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.harmonicpatterns'),
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='Trend_Analysis',
        ),
        migrations.AddField(
            model_name='analysis',
            name='Trend_Analysis',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trend_analysis', to='dashboard.trendanalysis'),
        ),
        migrations.AlterField(
            model_name='harmonicpatterns',
            name='value',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='trendanalysis',
            name='value',
            field=models.CharField(max_length=5000),
        ),
        migrations.DeleteModel(
            name='ChartPatterns',
        ),
        migrations.DeleteModel(
            name='TechnicalIndicators',
        ),
        migrations.DeleteModel(
            name='WaveAnalysis',
        ),
    ]
