# Generated by Django 3.2.7 on 2021-09-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_auto_20210924_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harmonicpatterns',
            name='value',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='trendanalysis',
            name='value',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
