# Generated by Django 3.2.7 on 2021-09-26 09:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20210924_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartPatterns',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('value', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FundamentalAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('value', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('balance', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('risk_on_balance', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalIndicators',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('value', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaveAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('value', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='harmonicpatterns',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='trendanalysis',
            name='owner',
        ),
        migrations.AlterField(
            model_name='analysis',
            name='Harmonic_Patterns',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harmonic_patterns', to='dashboard.harmonicpatterns'),
        ),
        migrations.AlterField(
            model_name='harmonicpatterns',
            name='value',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='trendanalysis',
            name='value',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='Chart_Patterns',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chart_patterns', to='dashboard.chartpatterns'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='Fundamental_Analysis',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fundamental_analysis', to='dashboard.fundamentalanalysis'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='Technical_Indicators',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_indicators', to='dashboard.technicalindicators'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='Wave_Analysis',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wave_analysis', to='dashboard.waveanalysis'),
        ),
        migrations.AddField(
            model_name='tradeposition',
            name='strategy',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade', to='dashboard.strategy'),
        ),
    ]
