# Generated by Django 3.2.7 on 2021-09-26 09:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_auto_20210926_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='balance',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='strategy',
            name='risk_on_balance',
            field=models.PositiveIntegerField(default='', validators=[django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
    ]
