# Generated by Django 3.2.7 on 2021-09-26 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_auto_20210926_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='risk_on_balance',
        ),
    ]
