# Generated by Django 3.2.7 on 2021-09-26 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_auto_20210926_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='balance',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
