# Generated by Django 3.2.7 on 2021-09-26 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_strategy_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='risk_on_balance',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
