# Generated by Django 3.2.7 on 2021-09-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_strategy_risk_on_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='value_risk',
            field=models.FloatField(null=True),
        ),
    ]
