# Generated by Django 3.2.7 on 2021-09-26 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_strategy_value_risk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeposition',
            name='strategy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade', to='dashboard.strategy'),
        ),
    ]
