# Generated by Django 3.2.7 on 2021-09-26 15:35

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_alter_tradeposition_strategy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeposition',
            name='date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)]),
        ),
    ]
