# Generated by Django 3.2.7 on 2021-09-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_alter_tradeposition_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeposition',
            name='date',
            field=models.DateField(),
        ),
    ]
