# Generated by Django 3.2.7 on 2021-09-26 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_delete_messages'),
        ('dashboard', '0030_alter_tradeposition_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
    ]
