# Generated by Django 3.2.7 on 2021-10-01 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_strategy_risk_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategy',
            old_name='risk_on_balance',
            new_name='risk_balance',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='value_risk',
        ),
    ]
