# Generated by Django 3.2.7 on 2021-10-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_strategy_value_risk_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeposition',
            name='strategy_alert',
            field=models.CharField(choices=[('risk_on_balance', 'risk on balance'), ('risk_on_position', 'risk on position')], max_length=500, null=True),
        ),
    ]
