# Generated by Django 3.2.7 on 2021-10-01 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_tradeposition_strategy_alert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradeposition',
            old_name='strategy_alert',
            new_name='strategyAlert',
        ),
    ]
