# Generated by Django 3.2.7 on 2021-10-01 19:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('dashboard', '0011_strategy_remainrisk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='remainRisk',
        ),
        migrations.CreateModel(
            name='RemainRisk',
            fields=[
                ('value', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile')),
                ('strategy', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remainrisk', to='dashboard.strategy')),
                ('trade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='remainrisk', to='dashboard.tradeposition')),
            ],
        ),
    ]
