# Generated by Django 3.2.7 on 2021-10-01 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_strategy_equity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RemainRisk',
        ),
    ]
