# Generated by Django 3.2.7 on 2021-10-02 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_remove_strategy_equity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategy',
            old_name='new_position_size',
            new_name='new_position_risk',
        ),
    ]
