# Generated by Django 3.2.7 on 2021-10-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_rename_new_position_size_strategy_new_position_risk'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeposition',
            name='rewardRisk',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
