import type { Metadata } from 'next';
import { Be_Vietnam_Pro, Quicksand } from 'next/font/google';
import './globals.css';

const quicksand = Quicksand({ subsets: ['latin'], display: 'swap' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${quicksand.className} bg-night-900 text-lg font-light text-night-100`}
      >
        {children}
      </body>
    </html>
  );
}
