version: '3.8'

services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - psqldb:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: on-failure

  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    environment:
      REDIS_PASSWORD: 'Secret'
    command: sh -c "redis-server --appendonly yes --protected-mode no"
    volumes:
      - redis:/data
    ports:
      - '6379:6379'
    restart: on-failure
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - '8001:8001'

volumes:
  psqldb:
  redis:
